#!/usr/bin/env python3
import sys, random

args = sys.argv[1:]
dict = []
password = ""
words = 4
caps = 0
num = 0
symbol = 0

with open("words.txt") as file:
	for item in file:
		dict.append(item)
dictLen = len(dict)

for i in range(len(args)):
	if args[i] == "-h":
               print("use ./xkcdpwgen with some flags")
	elif args[i] == "-w":
		words = int(args[i + 1])
	elif args[i] == "-c":
		caps = int(args[i + 1])
	elif args[i] == "-n":
		num = int(args[i + 1])
	elif args[i] == "-s":
		symbol = int(args[i + 1])

for i in range(words):
	word = dict[random.randint(0, dictLen -1)]

	if caps != 0:
		word = word.capitalize()
		caps -= 1
	if num != 0:
		rand_place = random.randint(0,2)
		rand_num = random.randint(0,9)
		
		if rand_place == 0:
			word += str(rand_num) + word
		elif rand_place == 1:
			put = random.randint(0, len(word) - 1)
			word = word[:put] + str(rand_num) + word[put:]
		else:
			word += str(rand_num)
		num -= 1
	if symbol != 0:
		rand_place = random.randint(0,2)
		symbols = "(~!@#$%^&*.:;)"
        	
		rand_sym = symbols[random.randint(0, len(symbols) - 1)]
		
		if rand_place == 0:
            		word += rand_sym + word
        	
		elif rand_place == 1:
            	
			put = random.randint(0, (len(word) - 1))
			word = word[:put] + rand_sym + word[put:]
		else:
			word += rand_sym
			symbol -= 1
	password += word

password = ''.join(password.splitlines())
print(password)
